
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_AXI_BRAM_TVG_DEVICE_ID,
		XPAR_AXI_BRAM_TVG_DATA_WIDTH,
		XPAR_AXI_BRAM_TVG_ECC,
		XPAR_AXI_BRAM_TVG_FAULT_INJECT,
		XPAR_AXI_BRAM_TVG_CE_FAILING_REGISTERS,
		0,
		XPAR_AXI_BRAM_TVG_UE_FAILING_REGISTERS,
		0,
		XPAR_AXI_BRAM_TVG_ECC_STATUS_REGISTERS,
		XPAR_AXI_BRAM_TVG_CE_COUNTER_WIDTH,
		XPAR_AXI_BRAM_TVG_ECC_ONOFF_REGISTER,
		XPAR_AXI_BRAM_TVG_ECC_ONOFF_RESET_VALUE,
		XPAR_AXI_BRAM_TVG_WRITE_ACCESS,
		XPAR_AXI_BRAM_TVG_S_AXI_BASEADDR,
		XPAR_AXI_BRAM_TVG_S_AXI_HIGHADDR,
		XPAR_AXI_BRAM_TVG_S_AXI_CTRL_BASEADDR,
		XPAR_AXI_BRAM_TVG_S_AXI_CTRL_HIGHADDR
	}
};


